---
title: "PS270 Final Project"
author: "Akrama Mohamed"
description: "My final project"

---


## Project thoughts

I am interested in exploring data related to making predictions or collecting data. 

## Final Project Milestone 2:

How may achieving a higher education influence voter turnout in elections?

For my research, I would like to investigate how achieving a higher education would mean a greater voter turnout. ( How may achieving a higher education influence voter turnout in elections?) This hypothesis is rooted in the theory that individuals who may have earned their college degrees or higher than compared to individuals for example who are high-school graduates; have a greater awareness of the election associated with higher voter turnout. Additionally, higher levels of education typically provide individuals with a better understanding of political systems, the importance of civic participation, and policies. With this exposure to diverse sources of information, individuals may feel empowered or influenced to cast their votes, than those individuals who may not have gotten the opportunity for a higher education. In this research, the primary explanatory variable is education level, which is the calculation of people's achieved education measured in the number of years of schooling. Variation in this variable is crucial, and the data set includes a wide range of education levels, allowing us to capture differences across educational attainment groups.Furthermore, the outcome variable is the voter turnout, with 1 being an indication of individual voting and 0 for did not vote, a two-category measure determining whether an individual voted in the most recent election. To conclude, regarding observed patterns, it can be noted that if there is a consistent link between higher levels of education and increased voter turnout, it would provide evidence in support of the proposed hypothesis. Conversely, if there is no correlation between education level and voter turnout, it would refute the hypothesis, suggesting that other variables may account for voting behaviors.


## Final Project Milestone 3:

```{r}
library(ggplot2)
library(tidyverse)


turnout <- read_csv("data/file_from_turnout.csv") 
turnout |>
  ggplot(mapping = aes(x = Voting Rates,
                       y = Presidential Election + 
  geom_point(color = "indianred") + 
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Voters Turnout by Education Level",
       x = "Educational Level Achieved",
       y = "The Voters Turnout")
  
  
  
  
  
  
  
  
                       
                       
ggplot(data = refugees,
mapping = aes(x = arrivals,
y = thermometer_muslimmigr)) +
geom_point(color = "black") +
geom_smooth(method = "lm", se = FALSE) +
labs(x = "Number of Refugee Arrivals per Capita",
       y = "Thermometer Scores about Muslim Immigrants")
```

